### PR TITLE
36 releases Jun 23 - Jan 24

### PR DESCRIPTION
**Pull request by rjthorne**
Added all new releases up to and including UTOTP

### CODE REVIEW

**Comment by rjthorne** [comment]
Obvs some changes will need to be made to the json data as the site progresses but thought I'd get them in to bring the list (semi)up to date at least

**Review by SpiritQuaddicted — CHANGES_REQUESTED** [review]
Wow! Thank you so much :)

Some changes would be nice:

- [x] `exceedslimits` -> `exceeds_quake_limits` for consistency with existing packages
  - It's a fairly stupid tag tbh, hopefully someone will design something nicer with specific limits later
- [ ] Trailing newlines at the ends of files please! Otherwise sites like GitHub will always complain. https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

# Dependencies
Dependencies need more information and specification. So far I only played around with Quoth. Check out https://github.com/Quaddicted/quaddicted-data/commit/d5160181868beed310ce82c98ed7e8043255aaa9

No idea if those tag names and formats make perfect sense and if we are missing more crucial info for package managers or similar tools. I modelled it after https://wiki.archlinux.org/title/PKGBUILD

So for the copper release it would be `release_group=copper, provides='copper=1.3.0', current_main_group_package=yes`, maybe also `version=1.3.0`.  
For packages that depend on this, it would be `depends=('copper=1.3.0')`.

For the AD dependency maybe `depends=('arcane_dimensions=1.80.1')`?

Ultimately those tags will require changing lots of other files to work but please ignore that mess for this PR, someone can do it later :)

**Comment by rjthorne** [comment]
I've recommitted the files with the changes made, hoping that shows up in the PR? Shout if not and I need to do something else

I've not done the AD/Alk dependencies yet as figured it would be neater to update the mod entries first, then make it a big job to get all the existing releases updated. Need more practice with github before attempting that!

**Review by SpiritQuaddicted — APPROVED** [review]

**Comment by SpiritQuaddicted** [comment]
Let's try what happens :D

**Comment by SpiritQuaddicted** [comment]
Nice, this worked well! The releases should all be listed on https://www.quaddicted.com/db/
Ignore the missing data for weighted order, ratings etc.

For some I screwed up the logic on the embedded comment threads, I will have to fix those manually. For the others it seems to work fine.

Please **do not post a comment** on those yet, otherwise everyone will see the thread in the forums and people will get confused :)

**Comment by SpiritQuaddicted** [comment]
Ah poop, the "bytes" values of all the old jsons is kilobytes for some reason. Yours are correct. I will fix that.

**Pull request merged**
