### PR TITLE
May 2024 release update

### PR DESCRIPTION
**Pull request by rjthorne**
All new releases (almost) from mid-Jan to mid-May, plus Drake for depends purposes. No descriptions as they will be added together with the others. My server used for hosting again.

Several old commits seemed to get caught up in this PR due to syncing issues but the number of changes is consistent with the latest one only.

### CODE REVIEW

**Comment by rjthorne** [comment]
Just added another commit as I didn't realise there was a new 'zipbasedir' tag, also realised I'd missed the slashes at the end of the install/extract field

**Comment by rjthorne** [comment]
Bit the bullet and committed my changes for release groups, depends, provides, patch, current main group package, version

I didn't do anything with the hipnotic/rogue/malice stuff, will add that to the issue tracker as a possible thing to look at in future

**Comment by SpiritQuaddicted** [comment]
Great, I will take a look tonight.

I had reintroduced `zipbasedir` to play with https://discuss.quaddicted.com/t/quake-one-click-installer/7491/1 and completely overlooked the nice "install -> extract" data bit we had already there... Sorry for that, I should have others review my commits as well! I will drop zipbasedir again at some point because that was dumb. Thank you for including it though, even if that was only there due to my misguided stupidity :D

**Comment by SpiritQuaddicted** [comment]
Wow, amazing work. Thank you!  
So many older releases had multiple versions too. I had no idea.

Technically I am pretty sure that I will not be able to merge this because of the older commits leading to a conflict. In the future best best use the synchronisation button in https://github.com/rjthorne/quaddicted-data/ before adding new commits. Are you able to `rebase` the commits? It might be way too complicated if you are not used to Git. I can do it myself on the weekend and merge afterwards, no issue, just shout! :)

Wishes:
- [ ] Please add trailing newlines again, otherwise they will need to be added later anyways. Like before ;)
- [ ] Your JSONs have a different order of the `link` tags. Somehow your code wants to sort `link:` *after* `link=`. In ASCII `:` comes before `=` and at least Python and jedit sort like that. Please keep that order as it is :)
- [ ] Some backslashes for special character encodings got turned into double backslashes, e.g. `"title=Zerst\\u00f6rer Turtlemap Pack"`, `"title=Xmas Jam 2017 - 1024\\u00b3 theme"` or `"author=Iikka \"Fingers\" Ker\\u00e4nen"`. Those should stay as they are.

I will do some minor fixes afterwards, nothing wrong with these but small improvements that came to mind while reviewing.

**Pull request closed without merging**
